name: sismique-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - ipywidgets
  - voila
  - pip
  - pip:
    - ipympl